version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "RomanNumeralConversion"
        Alias: "RomanNumeralConversionAlias"
        CurrentVersion: "1"
        TargetVersion: "2"
Hooks:
