version: 0.1
phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn install 
  post_build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket roman-numerals-deployment-art --output-template-file outputtemplate.yaml
      - echo Build completed on `date`
artifacts:
  files:
    - template.yaml
    - outputtemplate.yaml
  discard-paths: yes
