swagger: '2.0'
basePath: /Prod
info:
  title: RomanNumeralConverter
schemes:
- https
paths:
  /numerals/{numerals+}:
    get:
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:006393696278:function:RomanNumeralConverter/invocations
        httpMethod: POST
        type: aws_proxy
        responses: {}        