---
swagger: 2.0
basePath: /Prod
info:
  title: RomanNumeralConverter
schemes:
- https
paths:
  /numerals/{numerals+}:
    any:
      x-amazon-apigateway-auth:
        type: none
      produces:
      - application/json
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:[AWS_ACCOUNT_ID]:function:RomanNumeralConverter/invocations
        httpMethod: POST
        type: aws_proxy