swagger: '2.0'
basePath: /Prod
info:
  title: RomanNumeralConverter
schemes:
- https
paths:
  /numerals:
    get:
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:006393696278:function:RomanNumeralConverter/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
        responses: {}
    any:
      x-amazon-apigateway-auth:
        type: none
      produces:
      - application/json
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:006393696278:function:RomanNumeralConverter/invocations
        httpMethod: POST
        type: aws_proxy
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
        