AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  RomanNumeralConverter:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RomanNumeralConverter
      Timeout: 30
      Handler: com.thehammer.numerals.RomanNumeralConversion::handleRequest
      Runtime: java8
      CodeUri: target//numerals-0.0.1-SNAPSHOT.jar
      Policies:
        - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /numerals/{numerals+}
            Method: get
  ExampleApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: swagger.yaml
Outputs:
  ExampleApi:
    Description: API URI
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/numerals'
    Export:
      Name: ExampleApi